# docker-compose.yml
#
# This docker-compose file is configured for a local teaching environment.
# It is not intended for production use.

services:

# --- Provedor de contexto ---

  # Orion Context Broker é o principal componente do FIWARE
  orion:
    image: fiware/orion:4.2.0
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    restart: unless-stopped
    expose:
      - "1026"
    ports:
      - "1026:1026"
    command: -dbURI mongodb://mongo-db -logLevel WARN -noCache # Nível de log alterado para WARN
    volumes:
      - orion-log:/var/log/orion
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1
      interval: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Adicionando à rede
    networks:
      - fiware-network

# --- Agentes e interfaces de dispositivos ---

  # IoT Agent JSON é um agente que conecta dispositivos IoT ao Orion Context Broker
  iot-agent-json:
    image: fiware/iotagent-json:3.5.0
    hostname: iot-agent-json
    container_name: fiware-iot-agent-json
    depends_on:
      - mongo-db
      - mosquitto
    restart: unless-stopped
    expose:
      - "4041"
      - "7896"
    ports:
      - "4041:4041"
      - "7896:7896"
    environment:
      - "IOTA_CB_HOST=orion"
      - "IOTA_CB_PORT=1026"
      - "IOTA_NORTH_PORT=4041"
      - "IOTA_REGISTRY_TYPE=mongo-db"
      - "IOTA_TIMESTAMP=true" 
      - "IOTA_CB_NGSI_VERSION=v2" 
      - "IOTA_MONGO_HOST=mongo-db"
      - "IOTA_MONGO_PORT=27017"
      - "IOTA_MONGO_DB=iotagentjson"
      - "IOTA_HTTP_PORT=7896"
      - "IOTA_PROVIDER_URL=http://iot-agent-json:4041"
      - "IOTA_MQTT_HOST=mosquitto"
      - "IOTA_MQTT_PORT=1883"
      - "IOTA_LOG_LEVEL=WARN" # Nível de log definido como WARN
      - "IOTA_host_TRANSPORT=MQTT"
    healthcheck:
      test: curl --fail -s http://iot-agent-json:4041/iot/about || exit 1
      interval: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Adicionando à rede
    networks:
      - fiware-network

  # Eclipse Mosquitto é um broker MQTT que conecta dispositivos IoT ao IoT Agent JSON
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    expose:
      - "1883"
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Removendo 'default' e adicionando a nova rede
    networks:
      - fiware-network

# --- Banco de Dados ---

  # MongoDB é um banco de dados NoSQL usado para armazenar dados do Orion Context Broker, IoT Agent JSON e Cygnus
  mongo-db:
    image: mongo:6.0
    hostname: mongo-db 
    container_name: mongo-db
    restart: unless-stopped
    expose:
      - "27017" 
    ports:
      - "27017:27017" 
    volumes:
      - mongo-db:/data/db
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Adicionando à rede
    networks:
      - fiware-network
# --- Volumes ---

volumes: # Creates a volume to persit the data in the database
  mongo-db: 
  orion-log:
  mosquitto-data:
  mosquitto-log:

# --- Redes ---
networks:
  fiware-network:
    driver: bridge # O padrão bridge é adequado para comunicação em uma única máquina.